version: '3.3'
services:
  todo-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'todo'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - todo-db:/var/lib/mysql
volumes:
  todo-db: